name: Plugin Check
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Composer dependencies
        run: composer install --no-dev
      - name: Build
        run: |
          npm install
          npm run build
      - name: Run plugin check
        uses: wordpress/plugin-check-action@v1